
public class StringOps {
	public static void main(String[] args)
	{
		
	}
	public char findTheDifference(String s, String t) {
//	You are given two strings s and t.
//	String t is generated by random shuffling string s and then add one more letter at a random position.
//	Return the letter that was added to t.
        char[] a=s.toCharArray(), b=t.toCharArray();
        int sum_s=0,sum_t=0;
        for(char i:b)
        {
            sum_t+=(int)i;
        }
        for(char i:a)
        {
            sum_s+=(int)i;
        }
        return ((char)(sum_t-sum_s));
    }
}
